name: "ampere_duckdb_project"
version: "1.0.0"
profile: "ampere_duckdb"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  ampere_duckdb_project:
    +materialized: external         
    +format: parquet                
    +partition_by: ["load_date"]    
    +file_size: "128MB"
