name: ampere_duckdb_project
version: 1.0
config-version: 2
profile: ampere_duckdb_project

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  ampere_duckdb_project:
    +materialized: view    
    processing:
      +schema: silver
      +materialized: external
      +tags: ["processing"]
    business_logic:
      export_processing_to_mssql:
        +enabled: "{{ var('enable_mssql_export', false) }}"
        +tags: ["bl_export"]
        +materialized: table
        +alias: mssql_export_log