name: ampere_duckdb_project
version: 1.0
config-version: 2
profile: ampere_duckdb_project

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  ampere_duckdb_project:
    +materialized: view    
    processing:
      +schema: silver
      +materialized: external
    business_logic:
      +schema: gold