# Test project
name: ampere_project
version: "1.0"
config-version: 2

profile: ampere_project

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  ampere_project:
    +materialized: table
