name: ampere_duckdb_project
version: 1.0
config-version: 2
profile: ampere_duckdb_project

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  ampere_duckdb_project:
    +materialized: external         
    +format: parquet                
    +partition_by: ["load_date"]    
    +file_size: "128MB"

    processing:
      +schema: "silver"
      +tags: ["layer:processing"]

    business_logic:
      +schema: "gold"
      +tags: ["layer:business_logic"]
