ampere_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./local.duckdb
      threads: 4
      extensions: ["httpfs"]
      settings:
        s3_region: "us-east-1"
        s3_url_style: "path"
        s3_endpoint: "{{ env_var('MINIO_S3_ENDPOINT', 's3.minio.local') }}"
        s3_use_ssl: false
        s3_access_key_id: "{{ env_var('MINIO_ACCESS_KEY') }}"
        s3_secret_access_key: "{{ env_var('MINIO_SECRET_KEY') }}"
      external_root: "s3://ampere-prod-silver"
