Vagrant.configure("2") do |config|
  # Define nodes and their resources, including the desired private IP
  nodes = {
    "ampere-k8s-master" => { cpus: 2, memory: 4096, ip: "192.168.56.100" },   # master node
    "ampere-k8s-node1"  => { cpus: 2, memory: 4096, ip: "192.168.56.101" },  # SQL Server node
    "ampere-k8s-node2"  => { cpus: 2, memory: 4096, ip: "192.168.56.102" },  # MinIO, DuckDB, dbt node
    "ampere-k8s-node3"  => { cpus: 2, memory: 4096, ip: "192.168.56.103" },  # Airflow node
  }

  nodes.each do |name, opts|
    config.vm.define name do |node|
      # Mount SSH keys directory for passwordless access
      node.vm.synced_folder "/home/oppie/.ssh", "/home/vagrant/host_ssh", type: "virtualbox"

      # Additional shared folders for the master node
      if name == "ampere-k8s-master"
        node.vm.synced_folder "/home/oppie/gpg_key", "/home/vagrant/gpg_key", type: "virtualbox"
        node.vm.synced_folder "./ms-chart", "/home/vagrant/ms-chart", type: "virtualbox"
      end

      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = name
      node.vm.network "public_network", bridge: "wlp2s0"
      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = opts[:memory]
        vb.cpus = opts[:cpus]
      end

      # Run the bootstrap shell script as a provisioner
      node.vm.provision "shell", path: "provision/bootstrap.sh"
    end
  end
end
