Vagrant.configure("2") do |config|
  nodes = {
    "k8s-master" => { cpus: 2, memory: 8192 },
    "k8s-node1"  => { cpus: 2, memory: 8192 },
    "k8s-node2"  => { cpus: 2, memory: 8192 },
    "k8s-node3"  => { cpus: 2, memory: 8192 },
  }

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = name
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |vb|
        vb.name = name
        vb.memory = opts[:memory]
        vb.cpus = opts[:cpus]
      end
      node.vm.provision "shell", path: "provision/bootstrap.sh"
    end
  end
end
