[project]
name = "ampere-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "faker>=37.3.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "pyodbc>=5.2.0",
    "ruff>=0.11.13",
    "sqlalchemy>=2.0.41",
    "sqlalchemy-utils>=0.41.2",
]

[dependency-groups]
dev = [
    "apache-airflow-task-sdk==1.0.3",
    "pytest>=8.4.1",
    "ruff>=0.11.13",
]
