# All comments are in English.
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-app-{{ ts_nodash | lower }}
  namespace: ampere
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: an7on/ampere-spark-job-test
  imagePullPolicy: Always
  mainApplicationFile: local:///apps/test_spark_app.py
  sparkVersion: "4.0.0"

  # Prefer numeric overrides via Hadoop conf (applies before spark.*)
  hadoopConf:
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.endpoint: "http://minio:9000"
    fs.s3a.path.style.access: "true"
    fs.s3a.connection.ssl.enabled: "false"
    fs.s3a.connection.timeout: "60000"
    fs.s3a.connection.establish.timeout: "5000"
    fs.s3a.socket.timeout: "60000"
    fs.s3a.retry.interval: "5000"
    fs.s3a.attempts.maximum: "5"
    fs.s3a.threads.keepalivetime: "60000"

  sparkConf:
    spark.driver.extraClassPath: "/opt/spark/extra-jars/*"
    spark.executor.extraClassPath: "/opt/spark/extra-jars/*"

  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
    securityContext:
      runAsUser: 185
      runAsNonRoot: true
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
      - name: MINIO_USE_SSL
        value: "false"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey

  executor:
    instances: 2
    cores: 1
    memory: 1g
    serviceAccount: spark
    securityContext:
      runAsUser: 185
      runAsNonRoot: true

  nodeSelector:
    kubernetes.io/hostname: ampere-k8s-node3
