# All comments are in English.
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-app-{{ ts_nodash | lower }}
  namespace: ampere
spec:
  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey
  executor:
    instances: 2
    cores: 1
    memory: 1g
    serviceAccount: spark
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey
  type: Scala
  mode: cluster
  image: an7on/ampere-spark-scala
  imagePullPolicy: Always
  mainClass: Assortment
  mainApplicationFile: local:///apps/test-scala.scala
  sparkVersion: "4.0.0"

  sparkConf:

  deps:
    jars:
      - local:///opt/spark/work-dir/target/dependency/bundle-2.32.29.jar
      - local:///opt/spark/work-dir/target/dependency/hadoop-aws-3.4.1.jar
      - local:///opt/spark/work-dir/target/dependency/wildfly-openssl-2.2.5.Final.jar
  nodeSelector:
    kubernetes.io/hostname: ampere-k8s-node3
