# All comments are in English.
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-app-{{ ts_nodash | lower }}
  namespace: ampere
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: an7on/ampere-spark-base
  imagePullPolicy: Always
  mainApplicationFile: local:///apps/test_spark_app.py
  sparkVersion: "4.0.0"

  sparkConf:
    spark.driver.extraClassPath: "/opt/spark/extra-jars/*"
    spark.executor.extraClassPath: "/opt/spark/extra-jars/*"

  driver:
    cores: 1
    memory: 1g
    serviceAccount: spark
    securityContext:
      runAsUser: 185
      runAsNonRoot: true
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
      - name: MINIO_USE_SSL
        value: "false"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey

  executor:
    instances: 2
    cores: 1
    memory: 1g
    serviceAccount: spark
    securityContext:
      runAsUser: 185
      runAsNonRoot: true

  nodeSelector:
    kubernetes.io/hostname: ampere-k8s-node3
