apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-app-{{ ts_nodash | lower }}
  namespace: ampere
spec:
  driver:
    cores: 1
    coreRequest: "400m"
    memory: 1g
    serviceAccount: spark
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey
      MSSQL_PASS:
        name: mssql-sa-secret
        key: SA_PASSWORD        
  executor:
    instances: 2
    cores: 1
    coreRequest: "400m"
    memory: 1g
    serviceAccount: spark
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
      - name: NUM_PARTITIONS
        value: "10"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey
      MSSQL_PASS:
        name: mssql-sa-secret
        key: SA_PASSWORD
  type: Python
  mode: cluster
  image: an7on/ampere-mssql-minio
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/work-dir/test_mssql_to_minio.py"
  sparkVersion: "4.0.0"

  deps:
    jars:
      - local:///opt/spark/work-dir/dependency/bundle-2.32.29.jar
      - local:///opt/spark/work-dir/dependency/hadoop-aws-3.4.1.jar
      - local:///opt/spark/work-dir/dependency/wildfly-openssl-2.2.5.Final.jar
      - local:///opt/spark/work-dir/dependency/mssql-jdbc-13.2.0.jre11.jar
      - local:///opt/spark/work-dir/dependency/slf4j-simple-2.0.17.jar
  nodeSelector:
    kubernetes.io/hostname: ampere-k8s-node3
