apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-app-{{ ts_nodash | lower }}
  namespace: ampere
spec:
  sparkConf:
    "spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version": "2"
    "spark.sql.parquet.output.committer.class": "org.apache.hadoop.fs.s3a.commit.S3ACommitter"
    "spark.hadoop.fs.s3a.committer.name": "directory"
    "spark.hadoop.fs.s3a.committer.staging.unique-filenames": "true"
    "spark.hadoop.fs.s3a.committer.staging.tmp.path": "/tmp/s3a-committer"
  driver:
    cores: 4
    coreRequest: "400m"
    coreLimit: "800m"
    memory: 1g
    serviceAccount: spark
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
      - name: NUM_PARTITIONS
        value: "6"        
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey
      MSSQL_PASS:
        name: mssql-sa-secret
        key: SA_PASSWORD        
  executor:
    instances: 2
    cores: 4
    coreRequest: "400m"
    coreLimit: "1000m"
    memory: 1g
    serviceAccount: spark
    env:
      - name: MINIO_ENDPOINT
        value: "http://minio:9000"
      - name: MINIO_TEST_BUCKET
        value: "ampere-prod-raw"
      - name: NUM_PARTITIONS
        value: "6"
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: minio-creds
        key: accesskey
      AWS_SECRET_ACCESS_KEY:
        name: minio-creds
        key: secretkey
      MSSQL_PASS:
        name: mssql-sa-secret
        key: SA_PASSWORD
  type: Python
  mode: cluster
  image: an7on/ampere-mssql-minio
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "local:///opt/spark/work-dir/test_mssql_to_minio.py"
  sparkVersion: "4.0.0"

  deps:
    jars:
      - local:///opt/spark/work-dir/dependency/bundle-2.32.29.jar
      - local:///opt/spark/work-dir/dependency/hadoop-aws-3.4.1.jar
      - local:///opt/spark/work-dir/dependency/wildfly-openssl-2.2.5.Final.jar
      - local:///opt/spark/work-dir/dependency/mssql-jdbc-13.2.0.jre11.jar
  nodeSelector:
    kubernetes.io/hostname: ampere-k8s-node3
