apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: source-to-raw-{{ params.stream }}-{{ ts_nodash }}
  namespace: {{ params.namespace }}
spec:
  type: Python
  mode: cluster
  sparkVersion: "4.0.1"
  image: {{ params.image }}
  imagePullPolicy: {{ params.image_pull_policy }}
  imagePullSecrets:
    - ghcr-pull
  mainApplicationFile: local:///opt/spark/app/source_to_raw_etl.py
  arguments:
    - --tables
    - "{{ params.tables }}"
    - --table-config
    - '{{ params.table_config | tojson }}'
    - --groups-config
    - '{{ params.groups_config | tojson }}'
    - --schema
    - {{ params.schema }}
    - --run-date
    - "{{ ds }}"
    - --run-id
    - "{{ run_id }}-{{ ti.try_number }}"
    - --mode
    - "{{ params.mode }}"
    - --partition-key
    - "{{ params.partition_key }}"
    - --snapshot-partitioned
    - "{{ params.snapshot_partitioned }}"
    - --event-date-column
    - "{{ params.event_date_column }}"
    - --watermark-column
    - "{{ params.watermark_column }}"
    - --watermark-from
    - "{{ params.watermark_from }}"
    - --watermark-to
    - "{{ params.watermark_to }}"
    - --lookback-days
    - "{{ params.lookback_days }}"
    - --shuffle-partitions
    - "{{ params.shuffle_partitions }}"
    - --bucket
    - {{ params.bucket }}
    - --output-prefix
    - {{ params.output_prefix }}
    - --source-system
    - {{ params.source_system }}
    - --app-name
    - {{ params.app_name }}
    - --image
    - {{ params.image }}
  sparkConf:
    spark.driver.extraClassPath: "/opt/spark/ivy/*"
    spark.executor.extraClassPath: "/opt/spark/ivy/*"
    spark.jars: "local:///opt/spark/ivy/hadoop-aws-3.4.2.jar,local:///opt/spark/ivy/hadoop-common-3.4.2.jar,local:///opt/spark/ivy/hadoop-client-runtime-3.4.2.jar,local:///opt/spark/ivy/hadoop-client-api-3.4.2.jar,local:///opt/spark/ivy/bundle-2.40.16.jar,local:///opt/spark/ivy/postgresql-42.7.3.jar"
    spark.ui.enabled: "false"
    spark.hadoop.fs.s3a.endpoint: "{{ params.minio_endpoint }}"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "{{ params.minio_ssl_enabled }}"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
  volumes:
    - name: ivy-cache
      persistentVolumeClaim:
        claimName: ivy-cache
  restartPolicy:
    type: Never
  driver:
    cores: {{ params.driver_cores }}
    coreRequest: "{{ params.driver_core_request }}"
    memory: "{{ params.driver_memory }}"
    serviceAccount: {{ params.service_account }}
    nodeSelector:
      kubernetes.io/hostname: ampere-k8s-node4
    volumeMounts:
      - name: ivy-cache
        mountPath: /opt/spark/ivy
    env:
      - name: PGHOST
        value: "{{ params.pg_host }}"
      - name: PGPORT
        value: "{{ params.pg_port }}"
      - name: PGDATABASE
        value: "{{ params.pg_database }}"
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: pguser
            key: pguser
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: pgpass
            key: pgpass
      - name: MINIO_S3_ENDPOINT
        value: "{{ params.minio_endpoint }}"
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: MINIO_ACCESS_KEY
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: MINIO_SECRET_KEY
  executor:
    instances: {{ params.executor_instances }}
    cores: {{ params.executor_cores }}
    coreRequest: "{{ params.executor_core_request }}"
    memory: "{{ params.executor_memory }}"
    nodeSelector:
      kubernetes.io/hostname: ampere-k8s-node4
    volumeMounts:
      - name: ivy-cache
        mountPath: /opt/spark/ivy
    env:
      - name: PGHOST
        value: "{{ params.pg_host }}"
      - name: PGPORT
        value: "{{ params.pg_port }}"
      - name: PGDATABASE
        value: "{{ params.pg_database }}"
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: pguser
            key: pguser
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: pgpass
            key: pgpass
      - name: MINIO_S3_ENDPOINT
        value: "{{ params.minio_endpoint }}"
      - name: MINIO_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: MINIO_ACCESS_KEY
      - name: MINIO_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: minio-creds
            key: MINIO_SECRET_KEY
