from init_source_preparation.config import schema_init

schema = schema_init

clients_query = f"""
CREATE TABLE "{schema}"."clients"(
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fullname varchar(255) NOT NULL,
    preferred_store_id smallint,
    registration_date date,
    updated_at date DEFAULT NULL,
    churned boolean
)
"""

stores_query = f"""
CREATE TABLE "{schema}"."stores"(
    id smallint NOT NULL,
    city varchar(50) NOT NULL,
    store_name varchar(50) NOT NULL
)
"""

zones_query = f"""
CREATE TABLE "{schema}"."zones"(
    id smallint NOT NULL,
    store_id smallint NOT NULL,
    zone_name varchar(50) NOT NULL
)
"""

assortment_query = f"""
CREATE TABLE "{schema}"."assortment"(
    product_id smallint NOT NULL,
    store_id smallint NOT NULL
)
"""

costing_query = f"""
CREATE TABLE "{schema}"."costing"(
    product_id smallint NOT NULL,
    store_id smallint NOT NULL,
    avg_cost numeric(10,2) NOT NULL,
    valid_from date NOT NULL,
    valid_to date
)
"""

products_query = f"""
CREATE TABLE "{schema}"."products"(
    id integer NOT NULL,
    product_name varchar(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    unit_type varchar(50) NOT NULL,
    category_id smallint NOT NULL,
    chance numeric(4,2) NOT NULL,
    valid_from date NOT NULL,
    valid_to date
)
"""

product_categories_query = f"""
CREATE TABLE "{schema}"."product_categories"(
    id smallint NOT NULL,
    category_name varchar(50) NOT NULL
)
"""

payments_query = f"""
CREATE TABLE "{schema}"."payments"(
    order_id integer NOT NULL,
    amount numeric(12,4),
    method varchar(50),
    payment_status varchar(50),
    payment_date date
)
"""

delivery_tracking_query = f"""
CREATE TABLE "{schema}"."delivery_tracking"(
    order_id integer NOT NULL,
    courier_id smallint NOT NULL,
    delivery_status_id smallint,
    status varchar(50),
    status_datetime timestamp(2)
)
"""

delivery_resource_query = f"""
CREATE TABLE "{schema}"."delivery_resource"(
    id smallint NOT NULL,
    fullname varchar(50) NOT NULL,
    delivery_type_id smallint NOT NULL,
    store_id smallint NOT NULL,
    created_at date,
    updated_at date DEFAULT NULL,
    active_flag boolean NOT NULL
)
"""

delivery_type_query = f"""
CREATE TABLE "{schema}"."delivery_type"(
    id smallint NOT NULL,
    courier_type varchar(50) NOT NULL
)
"""

delivery_costing_query = f"""
CREATE TABLE "{schema}"."delivery_costing"(
    zone_id smallint NOT NULL,
    delivery_type_id smallint NOT NULL,
    tariff numeric(4,2) NOT NULL
)
"""

orders_query = f"""
CREATE TABLE "{schema}"."orders"(
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id integer,
    order_date date,
    order_source_id smallint,
    store_id smallint,
    total_amount numeric(12,4)
)
"""

order_product_query = f"""
CREATE TABLE "{schema}"."order_product"(
    order_id integer NOT NULL,
    order_date date,
    product_id integer NOT NULL,
    quantity numeric(6,2),
    sales_price numeric(10,2)
)
"""

order_status_history_query = f"""
CREATE TABLE "{schema}"."order_status_history"(
    order_id integer NOT NULL,
    order_status_id smallint NOT NULL,
    status_datetime timestamp(2) NOT NULL
)
"""

order_statuses_query = f"""
CREATE TABLE "{schema}"."order_statuses"(
    id smallint NOT NULL,
    order_status varchar(50) NOT NULL
)
"""

indexes_query = f"""
CREATE INDEX IF NOT EXISTS idx_orders_order_date
    ON "{schema}"."orders" (order_date, id);
CREATE INDEX IF NOT EXISTS idx_osh_orderid_statusdt
    ON "{schema}"."order_status_history" (order_id, status_datetime DESC);
CREATE INDEX IF NOT EXISTS idx_delivery_tracking_orderid
    ON "{schema}"."delivery_tracking" (order_id);
"""

table_queries = {
    "clients": {
        "query": clients_query,
        "type": "init",
    },
    "stores": {
        "query": stores_query,
        "type": "dict",
    },
    "zones": {
        "query": zones_query,
        "type": "dict",
    },
    "assortment": {
        "query": assortment_query,
        "type": "init",
    },
    "costing": {
        "query": costing_query,
        "type": "dict",
    },
    "products": {
        "query": products_query,
        "type": "dict",
    },
    "product_categories": {
        "query": product_categories_query,
        "type": "dict",
    },
    "payments": {
        "query": payments_query,
        "type": "gen",
    },
    "delivery_tracking": {
        "query": delivery_tracking_query,
        "type": "gen",
    },
    "delivery_resource": {
        "query": delivery_resource_query,
        "type": "init",
    },
    "delivery_type": {
        "query": delivery_type_query,
        "type": "dict",
    },
    "delivery_costing": {
        "query": delivery_costing_query,
        "type": "dict",
    },
    "orders": {
        "query": orders_query,
        "type": "gen",
    },
    "order_product": {
        "query": order_product_query,
        "type": "gen",
    },
    "order_status_history": {
        "query": order_status_history_query,
        "type": "gen",
    },
    "order_statuses": {
        "query": order_statuses_query,
        "type": "dict",
    },
    "indexes": {
        "query": indexes_query,
        "type": "index",
    },
}
