apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accesskey: {{ .Values.accesskey | b64enc | quote }}
  secretkey: {{ .Values.secretkey | b64enc | quote }}