---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql
spec:
  type: NodePort
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
      nodePort: {{ .Values.mssql.nodePort }}
  selector:
    app: mssql
