executor: CeleryExecutor

env:
  - name: MSSQL_PASSWORD
    value: $MSSQL_SECRET

images:
  airflow:
    repository: $AIRFLOW_REPO
    tag: latest
    pullPolicy: Always

nodeSelector:
  kubernetes.io/hostname: $NODE3_NAME

workers:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

  replicas: 2
  keda:
    enabled: true
    minReplicaCount: 2
    maxReplicaCount: 4
    pollingInterval: 30
    cooldownPeriod: 180
  resources:
    requests:
      cpu: "500m"
      memory: "768Mi"
    limits:
      cpu: "1"
      memory: "1536Mi"

config:
  celery:
    worker_concurrency: 2


triggerer:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS
  replicas: 2
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

redis:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

dags:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS
  gitSync:
    enabled: true
    repo: $GIT_REPO
    branch: master
    subPath: "dags"
    credentialsSecret: git-credentials
    ref: HEAD
    period: 5s

logs:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

postgresql:
  primary:
    persistence:
      storageClass: $DEFAULT_STORAGE_CLASS

webserver:
  enabled: true

apiServer:
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  service:
    type: NodePort
    ports:
      - name: api-server
        port: 8080
        targetPort: api-server
        nodePort: $AIRFLOW_NODEPORT
  env:
    - name: AIRFLOW__API__BASE_URL
      value: "http://airflow.local"

scheduler:
  replicas: 2
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

dagProcessor:
  replicas: 2
  resources:
    requests:
      cpu: "1"
      memory: "1.5Gi"
    limits:
      cpu: "2"
      memory: "3Gi"