executor: CeleryExecutor

env:
  - name: MSSQL_PASSWORD
    value: $MSSQL_SECRET

images:
  airflow:
    repository: $AIRFLOW_REPO
    tag: latest
    pullPolicy: IfNotPresent

nodeSelector:
  kubernetes.io/hostname: $NODE3_NAME

workers:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

triggerer:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

redis:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

dags:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS
  gitSync:
    enabled: true
    repo: $GIT_REPO
    branch: master
    subPath: "dags"
    credentialsSecret: git-credentials
    ref: HEAD
    period: 5s

logs:
  persistence:
    storageClassName: $DEFAULT_STORAGE_CLASS

postgresql:
  primary:
    persistence:
      storageClass: $DEFAULT_STORAGE_CLASS

webserver:
  enabled: true

apiServer:
  service:
    type: NodePort
    ports:
      - name: api-server
        port: 8080
        targetPort: api-server
        nodePort: $AIRFLOW_NODEPORT
  env:
    - name: AIRFLOW__API__BASE_URL
      value: "http://airflow.local"
